version: '2'
services:
  vault:
    image: docker.io/vault:v0.6.0
    container_name: sitch_vault
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_cert_file": "/etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem","tls_key_file":"/etc/letsencrypt/live/${SERVER_NAME}/privkey.pem"}},"default_lease_ttl": "7200h", "max_lease_ttl": "7200h"}'
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      sitch_elk:
        aliases:
          - ${SERVER_NAME}
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    command: server
    restart: "no"
  elasticsearch:
    image: docker.io/elasticsearch:5.5.2
    container_name: sitch-elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - /opt/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - sitch_elk
  logstash:
    image: docker.io/sitch/logstash:v0.10
    container_name: sitch-logstash
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - "elasticsearch:9200"
      - "influxdb:8086"
      - "vault:8200"
    environment:
      ES_URL: http://elasticsearch:9200
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      SLACK_USERNAME: ${SLACK_USERNAME}
      SLACK_ICON: ${SLACK_ICON}
      VAULT_URL: ${VAULT_URL}
      VAULT_TOKEN: ${VAULT_TOKEN}
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - sitch_elk
    depends_on:
      - elasticsearch
      - influxdb
      - vault
    restart: always
  kibana:
    image: docker.io/kibana:5.5.1
    container_name: sitch-kibana
    links:
      - "elasticsearch:9200"
    environment:
      ELASTICSEARCH_URL: http://sitch-elasticsearch:9200
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - sitch_elk
    depends_on:
      - elasticsearch
  influxdb:
    image: docker.io/influxdb:1.2.4
    container_name: sitch-influxdb
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
    volumes:
      - /opt/influxdb:/var/lib/influxdb
    networks:
      - sitch_elk
  chronograf:
    image: docker.io/chronograf:1.3
    container_name: sitch-chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - "influxdb:8086"
    volumes:
      - /opt/chronograf:/var/lib/chronograf
    networks:
      - sitch_elk
  kapacitor:
    image: docker.io/kapacitor:1.3.0
    container_name: sitch-kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - /opt/kapacitor:/var/lib/kapacitor
    links:
      - influxdb
    depends_on:
      - influxdb
    ports:
      - "9092:9092"
  web:
    image: docker.io/sitch/web:v0.9
    container_name: sitch-web
    ports:
      - "1000:1000"
      - "8443:8443"
    environment:
      SERVER_NAME: ${SERVER_NAME}
      KIBANA_URL: http://kibana:5601
      CHRONOGRAF_URL: http://chronograf:8888
    links:
      - "chronograf:8888"
      - "kibana:5601"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - sitch_elk
    depends_on:
      - chronograf
      - kibana

networks:
  sitch_elk:
    driver: bridge
